# syntax=docker/dockerfile:experimental
FROM golang:latest

RUN --mount=type=cache,target=/var/cache/apt \
    --mount=type=cache,target=/var/lib/apt \
    apt-get update && apt-get install -y zip jq

RUN --mount=type=bind,source=./deps,target=/tmp/deps \
    cd /tmp/deps/ && \
    ./install.sh

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    go install google.golang.org/protobuf/cmd/protoc-gen-go@latest